services:
  postgres:
    image: postgres:16
    container_name: datai-postgres-container
    restart: always
    environment:
      POSTGRES_DB: datai
      POSTGRES_USER: dataiuser
      POSTGRES_PASSWORD: dataipass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/sql:/docker-entrypoint-initdb.d
    networks:
      - datai_net

  adminer:
    image: adminer
    container_name: datai_adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - datai_net

volumes:
  postgres_data:

networks:
  datai_net:
    driver: bridge
