// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type Mutation struct {
}

type Query struct {
}

type UpsertUserInput struct {
	UID      string  `json:"uid"`
	Nickname *string `json:"nickname,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	UID       string  `json:"uid"`
	Nickname  *string `json:"nickname,omitempty"`
	Avatar    *string `json:"avatar,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}
